### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_resolution: 262144
video_resolution: 16384
trust_remote_code: true


### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
# freeze_trainable_layers: 0
deepspeed: /pfss/mlde/workspaces/mlde_wsp_KIServiceCenter/lhelff/LlavaGuard/scripts/train/zero3.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: LlavaGuard-DS-v24-oversampled
eval_dataset: LlavaGuard-DS-v24-eval
template: qwen2_vl
cutoff_len: 32768
vllm_maxlen: 131072
overwrite_cache: true
preprocessing_num_workers: 16

### output
run_name: QwenGuard2.5-v1.2-7b-run1
output_dir: /pfss/mlde/workspaces/mlde_wsp_KIServiceCenter/lhelff/ds/LlavaGuard/models/QwenGuard2.5-v1.2-7b-run1/v24
logging_steps: 1
save_strategy: epoch
save_steps: 1
plot_loss: true
overwrite_output_dir: true
report_to: wandb


### train
per_device_train_batch_size: 5
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
tf32: true
weight_decay: 0.1
ddp_timeout: 180000000
dataloader_drop_last: true
flash_attn: fa2

### eval
# val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 20
