### model
model_name_or_path: llava-hf/llava-onevision-qwen2-72b-ov-hf
image_resolution: 262144
video_resolution: 16384
trust_remote_code: true


### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
deepspeed: /pfss/mlde/workspaces/mlde_wsp_KIServiceCenter/lhelff/LlavaGuard/scripts/train/zero3.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: LlavaGuard-DS-v24-oversampled
eval_dataset: LlavaGuard-DS-v24-eval
template: qwen2_vl
cutoff_len: 32768
vllm_maxlen: 32768
overwrite_cache: true
preprocessing_num_workers: 16

### output
run_name: LlavaGuard-v1.2-72b-ov-run1
output_dir: /pfss/mlde/workspaces/mlde_wsp_KIServiceCenter/lhelff/ds/LlavaGuard/models/LlavaGuard-v1.2-72b-ov-run1/v24
logging_steps: 1
save_strategy: epoch
save_steps: 1
plot_loss: true
overwrite_output_dir: true
report_to: wandb


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 5
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
tf32: true
ddp_timeout: 180000000

### eval
per_device_eval_batch_size: 1
eval_strategy: epoch
eval_steps: 1
